### ISSUE TITLE
Instructions for using Digital Ocean Spaces for storage?

### ISSUE THREAD

**Issue by jebofponderworthy** [tagspaces/documentation#10]
I tried a variety of configurations, was not able to get it to work.  The ability seems rather clearly there.  If someone can tell me in general how to do it using the following, I'll be most happy to write it up formally in TagSpaces docs.

Space Settings:

xyzpdqabc
in xyzpdqabc / https://xyz.nyc3.digitaloceanspaces.com

It works fine in s3cmd, but I don't know how to translate that to TagSpaces' configuration fields.

**Comment by uggrock** [comment]
Here are tutorials for connecting other AWS S3 compatible storage: https://www.tagspaces.org/products/howtostart/
