### ISSUE TITLE
Android Version File Picker

### ISSUE THREAD

**Issue by hmcanady** [tagspaces/documentation#15]
Hi.

I created a location with the android version, using the file picker to select the location.  I wasn't able to add notes or perform operations on the files.  So I went to edit the location, and the filepath was shown in file:/// notation.  When I changed this to match the default locations (sdcard/XXX) it seemed to solve the problem.  I have also had a similar problem trying to move files using the file/folder picker.  I am running on a Samsung device with Android 11.  Please let me know if you need any further information.

Thanks!

**Comment by uggrock** [comment]
Hi, this issue is fixed in version 3.11.1 of the Android application.
