### ISSUE TITLE
Non-Scrolling Sidebar in the Docs

### ISSUE THREAD

**Issue by MarjaE2** [tagspaces/documentation#17]
I am trying to figure out how to use tagspaces. I can't read the docs here https://docs.tagspaces.org/ because the non-scrolling sidebar triggers my migraines.

Yes, I know it's a standard web design practice... I can't escape it.

**Comment by uggrock** [comment]
Hi,
you can consider using web browsers such as Firefox, which have a build-in reader-view mode for web sites:
https://support.mozilla.org/en-US/kb/firefox-reader-view-clutter-free-web-pages

Alternative you can use our browser extensions (https://www.tagspaces.org/products/webclipper/) to save the pages you need to read as HTML(use the "Save Editable Page")-button and read later those files in TagSpaces or any other HTML-viewer. The extensions will extract only the main content of the articles.

**Comment by MarjaE2** [comment]
I am using Firefox, with css to make Reader View accessible. Your documents site doesn't allow Reader View.

**Comment by uggrock** [comment]
The reader view is not accessible only in the start page, all other pages it works, see https://docs.tagspaces.org/installation/ for example.
