### ISSUE TITLE
 Updating Instructions for Portable Version  Outdated ? 

### ISSUE THREAD

**Issue by skyerjoe** [tagspaces/documentation#18]
https://docs.tagspaces.org/installation/#updating-the-portable-version 

Is the instruction for the Portable Version Outdated ? 

I havent found any tsprofile Folder so far. 

best regards

**Comment by Testing20134** [comment]
You only get tsprofile if you're running and operating tagspaces in portable mode. If you dont have that folders, that mean you have ran the program on normal mode this whole time.
