### ISSUE TITLE
Keep folder position

### ISSUE THREAD

**Issue by amineyarman** [tagspaces/documentation#25]
Hello! Thank you for this amazing tool. I've been looking for something like this for so long and I'm considering upgrading to pro version.

I just have a minor issue, but one that, if solved, can improve the experience a lot.

So my issue is that I have a folder with a lot of sub-folders. Each sub-folder contains files that I want to tag. When I go inside a sub-folder and go back to the parent folder, the scroll goes back to the top. 

So what would be amazing is if the scroll is kept at the same position when coming back to a parent folder. And even more amazing would be to have the last visited folder highlighted in some way. That's how it works for example in Windows file explorer.

Thanks a lot!

**Comment by uggrock** [comment]
Hello @Aminerman 
and thanks for your positive feedback and thanks for reporting this issue. It is already in our backlog, so I hope we can fix it soon.
Greetings!
