### ISSUE TITLE
Full text search is not available in 5.0.4 Pro

### ISSUE THREAD

**Issue by AKXF2020** [tagspaces/documentation#43]
Version 5.0.4 Pro
I create some html files and try to search by text. I've turned on the option:
![image](https://user-images.githubusercontent.com/63178001/198834009-8182b560-e63d-42f9-8657-7b98db5d4529.png)

Now I search "1A" and expect it could show this string exists in "ANK.html", but  it shows nothing. Additionally, there is no full-text search option  in the top.
![image](https://user-images.githubusercontent.com/63178001/198834102-5f4b49c9-6b14-44f9-b465-7c06667a415c.png)

**Comment by uggrock** [comment]
Can you try to search for a word which does not contain digits, maybe this is causing the issue. 
Once you have activated the full-text checkbox for the location, there is no place to deactivate in the search options.

**Comment by uggrock** [comment]
closing the issue, since it is not related to the docs
