### ISSUE TITLE
Feat. Request:  Replace Tag

### ISSUE THREAD

**Issue by ZebulonGlitch** [tagspaces/documentation#47]
I'm using this fine app to organize a ton of family photos.  I manage tag groups in the left panel, I love this program!  Good job guys. 

Then I accidentally labeled about 100 photos "Collorado" with two L's.  No sweat, i'll just do what i used to do in Digikam and replace the tag.  No feature.  I edited it to the correct spelling.  

To my horror, I realized I'd have to manually go edit every single old tag by either clicking, deleting and confirming, and then re-dragging the correct one, or clicking, editing, deleting an L, and then saving....  Either way it took 10 extremely unpleasant minutes to fix my error.

Am I an idiot and overlooking some replace mechanism?  Or is it not existing yet?  The app has no drop down menu for functions or commands, so I don't know where any power widgets might hide...  It's as easy to use as a smart phone app, but it's also sadly at least in this way, just as limited...

I'd recommend a switch called "Update all tags everywhere" when in the tag editing dialog.  Then it's similar in logic to the tag group "apply color" switch.

Thanks!

**Comment by tagspaces-amp** [comment]
Hi and thanks for your input! Can you please use our newly create forum for feature requests: https://tagspaces.discourse.group/c/feature-requests/6
In general this is the repository for the tagspaces documentation. Issues for the TagSpaces app should be reported here: https://github.com/tagspaces/tagspaces/issues
Greetings!

**Comment by ZebulonGlitch** [comment]
Yeah, sorry, I'm in the middle of cleaning it up, searching for existing bugs, commenting, etc..  Am closing these out as i go here on the documentation side. 

Might want to make the git hub link on the documentation page point to the main project, and not the documentation project.  Or at least make separate links.  It's that link that messed me up, and I went on autopilot.
