### ISSUE TITLE
Incorrect/malformed markdown/html in tutorials/notetaking

### ISSUE THREAD

**Issue by dixonge** [tagspaces/documentation#5]
This page is not rendering correctly:

https://docs.tagspaces.org/tutorials/notetaking#

If you click 'edit' you are taken here:

https://github.com/tagspaces/documentation/edit/master/tutorials/notetaking.md

Original page is here on the Tagspaces blog:

https://www.tagspaces.org/blog/tagspaces-evernote-alternative/

In the Markdown version, the tables are in incomplete HTML and the image references/paths include extra characters and leave the images blank. This produces an incomplete page in the Tagspaces documentation site.

Normally I would just fork and edit, but I was unsure if the page should remain in Markdown, to be rendered by the Tagspaces web site, or should be in html.

**Comment by dixonge** [comment]
Only 2 blog posts last year, and no one ever looked at this issue or responded in 2.5 years. Figures...

**Comment by uggrock** [comment]
The documentation was updated last year and now the page you are referring does not exists anymore. The edit buttons are currently working.
