### ISSUE TITLE
feature request: ADD a choice putting sidecar file in the SAME folder of a file instead of a .ts folder.

### ISSUE THREAD

**Issue by ccchan234** [tagspaces/documentation#7]
hi~

Many people like me use teracopy or other copy managers to copy/move/verify files.

if a file.doc and file.doc.sidecar is in the SAME folder, I can sort the file manager by filename,
then I can easily pick each PAIR of files for operation.

tagspaces NOW put the sidecar file into another .ts folder, makes this IMPOSSIBLE.

I understand the .ts folder is established, but put in SAME folder is more reasonable.

so what I ask is ADD a choice to put sidecar file in same folder.
Some people, who have special interest, may continue to use the .ts folders. 

thank you.

**Comment by uggrock** [comment]
topic created in the TS-forum: https://tagspaces.discourse.group/t/add-a-choice-putting-sidecar-file-in-the-same-folder-of-a-file-instead-of-a-ts-folder/74
